version: '2'

services:
  mysql:
    image: hub.c.163.com/library/mysql:5.7
    ports:
      - 3306:3306
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart:
      unless-stopped
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: hub.c.163.com/library/redis:4.0.1
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - '6379:6379'
    volumes:
      - /data/redis/conf/redis.conf:/etc/redis/redis.conf
      - /data/redis/data:/data 
  tomcat:
   image: tomcat:8.5.43-jdk8
   ports:
    - 8080:8080
   volumes:
    - /data/uploader/webapps:/usr/local/tomcat/webapps
    - /data/uploader/logs:/usr/local/tomcat/logs      
